version: '3.4'

services:
  waes.diff.api:
    image: ${DOCKER_REGISTRY-}waesdiffapi
    build:
      context: .
      dockerfile: Waes.Diff.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "57270:80"
      - "44348:443"
    depends_on:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

